spring:
 datasource:
  type: com.alibaba.druid.pool.DruidDataSource
  url: jdbc:mysql://127.0.0.1:3306/graduation?characterEncoding=utf8
  driver: com.mysql.jdbc.Driver
  username: root
  password: root
  #配置监控统计拦截的filters，去掉后监控界面sql将无法统计,'wall'用于防火墙
  filters: stat,wall,log4j
  #最大活跃数
  maxActive: 20
  #初始化数量
  initailSize: 1
  #最大连接等待超时时间
  maxWait: 60000
  #打开PSCache，并且指定每个连接PSCache的大小
  poolPreparedStatements: true
  maxPoolPreparedStatementPerConnectionSize: 20
  #通过connectionPropertise属性来打开mergeSql功能，慢SQL记录
  connectionProperties: druid.stat.mergeSql=true;druid.stat.showSqlMillis=5000
  minldle: 1
  timeBetweenEvictionRunsMillis: 60000
  minEvictableldleTimeMillis: 300000
  validationQuery: select 1 from dual
  testWhileldle: true
  testOnBorrow: false
  testOnReturn: false
 jpa:
  properties:
   hibernate:
    show_sql: true
    format_sql: true